import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:super_plus/components/dialog_page_back_button.dart';
import 'package:super_plus/components/puzzle_captcha/index.dart';
import 'package:super_plus/const/gutter.dart';
import 'package:super_plus/helpers/dialog.dart';
import 'package:super_plus/models/user.dart';
import 'package:super_plus/pages/login/widgets/login_account.dart';
import 'package:super_plus/pages/login/widgets/login_agreement_confirmation.dart';
import 'package:super_plus/pages/login/widgets/login_phone.dart';
import 'package:super_plus/pages/login/widgets/login_welcome.dart';
import 'package:super_plus/pages/login/widgets/login_oauth.dart';
import 'package:super_plus/pages/login/widgets/login_terms.dart';
import 'package:super_plus/pages/login/widgets/login_agreement.dart';

part './controller.dart';
part './binding.dart';
part './view.dart';
